title: Mildred Maweuena Tseh
logo: https://github.com/Midge-commits/Portfolio/blob/main/Build/pict.png?raw=true

description : A detail-oriented Data Analyst who loves exploring data, , I specialize in data analysis, visualization, and reporting, helping businesses and teams make informed, strategic decisions.
show_downloads: true
theme : jekyll-theme-minimal

