title: Mildred Maweuena Tseh
logo: Midge-commits/Build?\/picture.jnp

description : A detail-oriented Data Analyst who loves exploring data, , I specialize in data analysis, visualization, and reporting, helping businesses and teams make informed, strategic decisions.
show_downloads: true
theme : jekyll-theme-minimal

